[add] a new Summary post
FreeCodeCamp-Chengdu/Wiki pull request #28
Opened 2020-10-30 01:28 UTC by LiJiahaoCoder

添加CosCon's 2020 x FCC成都社区大会总结《星星之火，可以燎原》

2020-10-30 14:39 UTC, TechQuery requested changes

2020-10-30 14:39 UTC, TechQuery commented on _posts/Article/Summary/A-Solitary-Spark-And-Wars-Begin.md
> +# 星星之火，可以燎原
参考一下去年大会总结文章开头的元数据写法
https://github.com/FreeCodeCamp-Chengdu/Wiki/blob/master/_posts/Article/Summary/Web-Conf-2019-Open-Source.md
然后在本地跑起来看一下效果。

2020-10-30 14:43 UTC, TechQuery requested changes

2020-10-30 14:43 UTC, TechQuery commented on _posts/Article/Summary/A-Solitary-Spark-And-Wars-Begin.md
> +![](../_posts/A-Solitary-Spark-And-Wars-Begin/a1bh4uxvyio.jpg)
本文章的素材图可以直接用 Hexo 自定义标签
https://hexo.io/docs/tag-plugins#Include-Assets

2020-10-31 02:31 UTC, LiJiahaoCoder commented on _posts/Article/Summary/A-Solitary-Spark-And-Wars-Begin.md
> +# 星星之火，可以燎原
已添加

2020-10-31 02:31 UTC, LiJiahaoCoder commented on _posts/Article/Summary/A-Solitary-Spark-And-Wars-Begin.md
> +![](../_posts/A-Solitary-Spark-And-Wars-Begin/a1bh4uxvyio.jpg)
已替换

2020-11-01 06:11 UTC, TechQuery requested changes

2020-11-01 06:11 UTC, TechQuery commented on _posts/Article/Summary/A-Solitary-Spark-And-Wars-Begin.md
> +  - 牛牛
在[志愿者数据](https://github.com/FreeCodeCamp-Chengdu/Wiki/blob/master/_data/volunteer.yml)文件里加上你的 GitHub 账号，然后这里写你的 GitHub ID

2020-11-01 06:11 UTC, TechQuery commented on _posts/Article/Summary/A-Solitary-Spark-And-Wars-Begin.md
> +## 星星之火，可以燎原
开头**元数据**里的 `title` 就会生成全文标题，不需要多一级内容中的大标题了

2020-11-01 14:26 UTC, TechQuery approved these changes

2020-11-01 14:27 UTC, merged