Modern git commands and features you should be using
FreeCodeCamp-Chengdu/Wiki pull request #60
Opened 2024-03-23 14:45 UTC by luojiyin1987

Closed #57

2024-03-27 07:58 UTC, luojiyin1987 commented
已经翻译完

2024-04-04 17:09 UTC, TechQuery requested changes
在本地 IDE 执行一下格式化。

2024-04-04 17:09 UTC, TechQuery commented on _posts/Article/Translation/Modern-Git-Commands-and-Features-You-Should-Be-Using.md
> +# 你应该使用的现代 Git 命令和功能
```suggestion
---
title: 你应该使用的现代 Git 命令和功能  
author: MARTINMa  
authorURL: https://martinheinz.dev/  
originalURL: https://martinheinz.dev/blog/109  
translator:  luojiyin1987
reviewer: TechQuery
---
```
此处的 YAML 格式称作 front matter，会被主仓库里的网站生成器解析，生成对应文章的网页。

2024-04-04 17:09 UTC, TechQuery commented on _posts/Article/Translation/Modern-Git-Commands-and-Features-You-Should-Be-Using.md
> +如果你搜索一些与 `git` 相关的问题，你很可能会在 `StackOverflow` 上找到有几千个向上投票的答案的问题。虽然这个答案很可能仍然有效，但很可能已经过时，因为它是 10 年前写的。因此，可能还有更好、更简单、更容易的方法。因此，当遇到一些 `git` 问题时，我建议查看 `git` 文档，了解最新的命令，这些命令都有很多很好的示例，或者浏览 `man` 页面，了解多年来添加到老命
```suggestion
如果你搜索一些与 `git` 相关的问题，你很可能会在 StackOverflow 上找到有几千个向上投票的答案的问题。虽然这个答案很可能仍然有效，但很可能已经过时，因为它是 10 年前写的。因此，可能还有更好、更简单、更容易的方法。因此，当遇到一些 `git` 问题时，我建议查看 `git` 文档，了解最新的命令，这些命令都有很多很好的示例，或者浏览 `man` 页面，了解多年来添加到老命令中的很多标记（flags）和选项（options）。
```

2024-04-05 07:22 UTC, TechQuery requested changes
前面还有一条没改完，直接使用我建议的代码。

2024-04-05 07:22 UTC, TechQuery commented on _posts/Article/Translation/Modern-Git-Commands-and-Features-You-Should-Be-Using.md
> +我们所有软件工程师每天都在使用 git，但大多数人只接触过最基本的命令，如 add, commit, push 或者 pull, 好像还停留在 2005 年。
```suggestion
我们所有软件工程师每天都在使用 `git`，但大多数人只接触过最基本的命令，如 `add`、`commit`、`push` 或者 `pull`, 好像还停留在 2005 年。
```
此段文字的语义就是在讲命令，应该用行内代码块，并且英文逗号应该在罗列时变为中文顿号。

2024-04-05 10:08 UTC, TechQuery commented on _posts/Article/Translation/Modern-Git-Commands-and-Features-You-Should-Be-Using.md
> +# 你应该使用的现代 Git 命令和功能
```suggestion
```
上面元数据里有了，会自动渲染

2024-04-05 10:09 UTC, TechQuery commented on _posts/Article/Translation/Modern-Git-Commands-and-Features-You-Should-Be-Using.md
> +### Switch
```suggestion
## Switch
```
全文没有 2 级标题，因此所有 3 级都要改成 2 级。

2024-04-05 11:25 UTC, TechQuery approved these changes

2024-04-05 11:25 UTC, merged