developer tools secrets that shouldnt be secrets
FreeCodeCamp-Chengdu/Wiki pull request #61
Opened 2024-03-27 04:21 UTC by luojiyin1987

Closed #43

2024-03-27 07:58 UTC, luojiyin1987 commented
已经翻译完

2024-05-25 14:14 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +### 像 jQuery 一样 : $() and $$()
这里哪里来的 jQuery？

2024-05-25 14:15 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +## 3. 你可以在浏览器外登录 - VS code 调试器
这句翻译是有问题的，自己检查一下

2024-05-25 14:28 UTC, luojiyin1987 commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +### 像 jQuery 一样 : $() and $$()
意译，  跟 JQuery 一样锋利，  使用方法也类似jQuery。

2024-05-25 14:31 UTC, luojiyin1987 commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +## 3. 你可以在浏览器外登录 - VS code 调试器
You can log outside the browser – VS Code debugger ？ 
请问 你怎么翻译？

2024-05-25 16:26 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +## 3. 你可以在浏览器外登录 - VS code 调试器
直译结果
```
你可以在浏览器之外记录 - VS Code 调试器 ？
```

意译结果
```
您是否可以在浏览器之外使用 VS Code 调试器进行日志记录？
```
 这里仔细看一下，log 一般不会翻译成 登录，这里一直在说做日志

2024-05-25 16:49 UTC, too reviewed
注意一些翻译上的小细节

2024-05-25 16:49 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +### 你想输出什么 logging?
这里我给出建议的翻译是：
### What is that you’re logging?

什么是你正在记录的内容？

2024-05-25 16:49 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +复制和粘贴这些信息时，表格结构会保持不变，因此它是将数据导入 `Excel` 或 `Word` 等的绝佳工具。
供参考：
原文翻译：
```
表结构在复制和粘贴此信息时得以保留，这使其成为一个很好的工具，例如将数据导入Excel或Word。
```

意译结果
```
当您复制并粘贴这些信息时，表格结构会被保留，这使得它成为一个非常方便的工具，比如可以轻松地将数据导入到 Excel 或 Word 中。
```

2024-05-25 16:49 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +## 2. 您可以在没有源访问权限的情况下进行日志记录,实时表达式和日志点
`-` 换成 ， 和其他的风格不统一可好？

2024-05-25 16:49 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +## 4. 您可以向任何网站注入代码。片段（Snippets）和重写（Overrides）
`-` 变成 。

2024-05-25 16:49 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +## 7. 你们是开发人员工具的受众和客户！
每个小标题下面括号里的能翻译的还是需要翻译的吧？ 这里不翻译的理由是什么？ 之前的一些 (Chromium Browsers) 这样的建议翻译成 (Chromium 浏览器)，请自行检查

2024-05-25 16:49 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +[分享到 Mastodom](https://mastodon.social/share?text=Developer) 不应该是秘密的工具秘密 https://christianheilmann.com/2021/11/01/developer-tools-secrets-that-shouldnt-be-secrets/)
这里破坏了原有的链接标记，请对照恢复

2024-05-25 16:49 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +## 1. Console 远不止是 log()!
Console 要么不翻，要么都翻译？

2024-05-25 16:54 UTC, too commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +title: 揭开浏览器开发工具的秘密
给出一个建议翻译：开发者工具中不应该是秘密的秘密

2024-05-26 03:23 UTC, luojiyin1987 commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +## 4. 您可以向任何网站注入代码。片段（Snippets）和重写（Overrides）
?   看不明白

2024-05-26 03:35 UTC, luojiyin1987 commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +[分享到 Mastodom](https://mastodon.social/share?text=Developer) 不应该是秘密的工具秘密 https://christianheilmann.com/2021/11/01/developer-tools-secrets-that-shouldnt-be-secrets/)
爬虫 没识别准确。

2024-05-26 03:38 UTC, luojiyin1987 commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +title: 揭开浏览器开发工具的秘密
我保留我的翻译

2024-06-27 14:46 UTC, TechQuery requested changes

2024-06-27 14:46 UTC, TechQuery commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
>  console.<span style="color: #660066;">log</span><span style="color: #009900;">(</span>height<span style="color: #009900;">)</span></pre></td></tr></tbody></table>
转成 Markdown 代码块

2024-06-27 14:46 UTC, TechQuery commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +添加 "console.log() "的常规方法是将其放在代码中想要获取信息的地方。但你也可以深入了解你无法访问和更改的代码。[Live 表达式](https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/console/live-expressions) 是在不更改代码的情况下记录信息的好方法。它们还能记录不断变化的值，
```suggestion
添加 `console.log()` 的常规方法是将其放在代码中想要获取信息的地方。但你也可以深入了解你无法访问和更改的代码。[Live 表达式](https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/console/live-expressions) 是在不更改代码的情况下记录信息的好方法。它们还能记录不断变化的值，而不会让控制台满屏日志，从而降低产品的运行速度。你可以从下面的截屏中看到它们的不同之处：
```

2024-06-27 14:46 UTC, TechQuery commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
>  [![Inspecting the Chromium Developer tools with another instance of the developer tools](https://christianheilmann.com/wp-content/uploads/2021/11/Slide36.png)](https://christianheilmann.com/wp-conten
图片注释也要翻译

2024-06-27 14:46 UTC, TechQuery commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
>  (Microsoft Edge via a VS Code extension)
专有名词之外都要翻译

2024-06-27 16:18 UTC, TechQuery requested changes

2024-06-27 16:18 UTC, TechQuery commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +毫无疑问，除了元素工具，控制台是浏览器开发者工具中使用最多的部分。特别是，人们喜欢通过在代码中添加 "console.log()/"来调试，以了解发生了什么。虽然这样做存在一些问题，也有更好的调试脚本的方法，但既然人们都这么做了，那我们就来谈谈如何让这种体验变得更好。
```suggestion
毫无疑问，除了元素工具，控制台是浏览器开发者工具中使用最多的部分。特别是，人们喜欢通过在代码中添加 `console.log()` 来调试，以了解发生了什么。虽然这样做存在一些问题，也有更好的调试脚本的方法，但既然人们都这么做了，那我们就来谈谈如何让这种体验变得更好。
```

2024-06-27 16:18 UTC, TechQuery commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +[![控制台工具中的过滤选项][6]](https://christianheilmann.com/wp-content/uploads/2021/10/console-filter-dropdown.msft_.png)
要缩成引用的是超链接而非图片的网址。

2024-06-27 16:18 UTC, TechQuery commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +(适用于所有浏览器，但此处显示的渠道仅限于 Microsoft Edge）
```suggestion
（适用于所有浏览器，但此处显示的渠道仅限于 Microsoft Edge）
```

2024-06-27 17:47 UTC, TechQuery requested changes

2024-06-27 17:47 UTC, TechQuery commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +![控制台工具中的过滤选项][6]
我指的是这么写：
```markdown
[![image](/image/URL)][1]

[1]: /link/URL
```

2024-06-28 01:15 UTC, luojiyin1987 commented on _posts/Article/Translation/developer-tools-secrets-that-shouldnt-be-secrets.md
> +![控制台工具中的过滤选项][6]
已经调整

2024-06-28 08:39 UTC, TechQuery approved these changes

2024-06-28 08:39 UTC, merged