web scraping and parsing experiment with ai openai
FreeCodeCamp-Chengdu/Wiki pull request #63
Opened 2024-03-27 14:49 UTC by luojiyin1987

Closed #46

2024-04-06 04:35 UTC, too commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +我一直很惊讶 OpenAI 的 chatGPT 在回答问题方面的表现，以及 Dall-e 3 制作精美图片的能力。现在，有了新的模型，让我们看看人工智能如何处理我们的网络搜索任务，特别是解析搜索引擎结果。我们都知道，从原始 HTML 中钻取解析数据通常会很麻烦。但是，如果有一种方法可以将这一艰苦的过程变得轻而易举呢？
drill—parsing 翻译成「钻取解析」 ，换成「提取解析」会不会更好一点

2024-04-06 04:40 UTC, too commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +> 最近（2023 年 11 月），OpenAI 团队召开了 [首次开发者大会：DevDay（请先随意观看）](https://www.youtube.com/watch?v=U9mJuUkhUzk)。其中一个令人兴奋的公告是 GPT-4 的更大背景。新的 GPT-4 Turbo 型号功能更强、更便宜，而且支持 128K 上下文窗口。
最近（2023年11月），OpenAI团队举办了他们的[首次开发者大会：DevDay（欢迎先观看）](https://www.youtube.com/watch?v=U9mJuUkhUzk)。其中一个令人兴奋的消息是关于GPT-4更广泛应用领域的公告。新推出的GPT-4 Turbo模型更加强大、价格更实惠，并支持128K上下文窗口。 

```
Feel free to watch it first 翻译成（欢迎先观看）会不会好一点。a larger context 我认为是说GPT-4 有更大的上下文窗口，后文正好说明了这一点，而不是更大的背景
```

2024-04-06 04:41 UTC, too commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +来自 OpenAI 的人工智能网络搜索封面插图。
我用ChatGPT 3.5 得到的结果是「封面插图：OpenAI 的 AI 网络爬虫」，这样似乎好点？

2024-04-06 04:48 UTC, too commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +> 请记住，人工智能的任务只是解析原始 HTML 数据，而不是自己进行 `网络扫描`。
这里 `web scraping` 翻译成 “网页抓取” 或者 “网络数据抓取” 更好？

2024-04-06 04:49 UTC, too commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +- 从 Google MAPS 返回本地结果数据。
这里“结果”可能太简洁了，不太直观，加上“搜索” 成 “搜索结果” 如何？ 上面的 有机结果 也是

2024-04-06 04:50 UTC, too commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +如果您不想阅读整篇文章，下面是我们使用 OpenAI API（新 GPT-4）模型进行网络搜刮实验的利弊总结：
和上面一样，这里 web scraping 翻译成 “网页抓取” 或者 “网络数据抓取” 更好？

2024-04-06 04:53 UTC, too commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +- 与手动解析所需的开发时间相比，刮取原始 HTML 的能力无疑是一个巨大的优势。
这一段 和上面一样，搜刮 换成 抓取好一点？ 还有 最后一句 翻译成 “相较于手动解析，提取原始HTML绝对节省了开发时间。“ 这样或者“与手动解析相比，能够抓取原始 HTML 绝对是一个巨大优势。”如何？

2024-04-06 08:15 UTC, luojiyin1987 commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +- 从 Google MAPS 返回本地结果数据。
有机结果  我改成 相关结果  。  本地结果数据  改成   当地搜索结果

2024-04-06 10:34 UTC, too commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +> 最近（2023 年 11 月），OpenAI 团队召开了 [首次开发者大会：DevDay（请先随意观看）](https://www.youtube.com/watch?v=U9mJuUkhUzk)。其中一个令人兴奋的公告是 GPT-4 的更大背景。新的 GPT-4 Turbo 型号功能更强、更便宜，而且支持 128K 上下文窗口。
这个怎么看？ `a larger context 我认为是说GPT-4 有更大的上下文窗口，后文正好说明了这一点，而不是更大的背景` ？「更大的背景」 似乎是不对的

2024-04-06 10:39 UTC, too commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +截图 toscrape books，是第一个网络搜索目标
web scraping 网络抓取？

2024-04-06 10:40 UTC, luojiyin1987 commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +> 最近（2023 年 11 月），OpenAI 团队召开了 [首次开发者大会：DevDay（请先随意观看）](https://www.youtube.com/watch?v=U9mJuUkhUzk)。其中一个令人兴奋的公告是 GPT-4 的更大背景。新的 GPT-4 Turbo 型号功能更强、更便宜，而且支持 128K 上下文窗口。
刚才没看到 ， 已经修改

2024-04-09 20:21 UTC, TechQuery requested changes

2024-04-09 20:21 UTC, TechQuery commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> -<!-- more -->
此处保留，以便官网渲染器在列表页只显示摘要。

2024-04-09 20:21 UTC, TechQuery commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
>  #### [Hilman Ramadhan](/blog/author/hilman/)
```suggestion
**[Hilman Ramadhan](/blog/author/hilman/)**
```
链接改为原文网页中的绝对地址。

2024-04-09 20:21 UTC, TechQuery commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +**优点**
```suggestion
### 优点
```
下同

2024-04-10 03:10 UTC, TechQuery approved these changes

2024-04-10 04:08 UTC, too commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +###问题:
差一个空格吧？

2024-04-10 05:46 UTC, luojiyin1987 commented on _posts/Article/Translation/web-scraping-and-parsing-experiment-with-ai-openai.md
> +- [![Hilman Ramadhan](/blog/content/images/size/w100/2023/10/profile-picture.png)](/blog/author/hilman/)
如果换成原站的 URL 还要调整 头像的显示样式

2024-04-10 06:26 UTC, merged