browser-debugging-tricks
FreeCodeCamp-Chengdu/Wiki pull request #70
Opened 2024-04-13 03:27 UTC by luojiyin1987

Closed #49

2024-05-06 18:55 UTC, TechQuery requested changes

2024-05-06 18:55 UTC, TechQuery commented on _posts/Article/Translation/browser-debugging-tricks.md
>  class Dog {2  bark(count) {3    /* ... */4  }5}
```suggestion
class Dog {
  bark(count) {
    /* ... */
  }
}
```
此处是高亮的代码行号乱入

2024-05-06 18:55 UTC, TechQuery commented on _posts/Article/Translation/browser-debugging-tricks.md
> +```javascript
```suggestion
```text
```

2024-05-06 18:55 UTC, TechQuery commented on _posts/Article/Translation/browser-debugging-tricks.md
> +debugger; fn(1);
```suggestion
debugger;
fn(1);
```

2024-05-06 18:55 UTC, TechQuery commented on _posts/Article/Translation/browser-debugging-tricks.md
> +然后 `进入下一个函数调用(Step into next function call)`，以调试 `fn` 的实现。
```suggestion
然后“进入下一个函数调用 (Step into next function call)”，以调试 `fn` 的实现。
```
前者并非代码概念

2024-05-06 18:55 UTC, TechQuery commented on _posts/Article/Translation/browser-debugging-tricks.md
> +另外，请注意，这种方法无法处理直接调用 `window.location.replace/assign` 的情况，因为页面在赋值后会立即销毁，所以没有任何调试内容。如果你仍然想要查看这些重定向的原网址 (并在重定向时调试你的状态)，在 Chrome 中你可以使用 `debug` 来调试相关的方法：
```suggestion
另外，请注意，这种方法无法处理直接调用 `window.location.replace/assign` 的情况，因为页面在赋值后会立即销毁，所以没有任何调试内容。如果你仍然想要查看这些重定向的原网址（并在重定向时调试你的状态），在 Chrome 中你可以使用 `debug` 来调试相关的方法：
```

2024-05-06 18:55 UTC, TechQuery commented on _posts/Article/Translation/browser-debugging-tricks.md
> +如果你有一个对象，并想知道它的某个属性何时被读取，可以使用一个带有 `debugger` 调用的对象获取器。例如，将 `{configOption: true}` 转换为 `{get configOption() { debugger; return true; }}` (在原始源代码中或使用条件断点)。
```suggestion
如果你有一个对象，并想知道它的某个属性何时被读取，可以使用一个带有 `debugger` 调用的对象获取器。例如，将 `{configOption: true}` 转换为 `{get configOption() { debugger; return true; }}`（在原始源代码中或使用条件断点）。
```

2024-05-06 18:55 UTC, TechQuery commented on _posts/Article/Translation/browser-debugging-tricks.md
> +-   资源的元数据 (如图像)：`copy(performance.getEntriesByType("resource"))`
```suggestion
-   资源的元数据（如图像）：`copy(performance.getEntriesByType("resource"))`
```

2024-05-06 18:55 UTC, TechQuery commented on _posts/Article/Translation/browser-debugging-tricks.md
> +在 DOM 检查器中按下 `ctrl+\` (Chrome/Windows) 可以随时暂停 JS 的执行。这样您就可以检查 DOM 的快照，而不必担心 JS 会改变 DOM 或事件 (如鼠标悬停) 会导致 DOM 从您脚下发生变化。
```suggestion
在 DOM 检查器中按下 <kbd>ctrl</kbd> + <kbd>\</kbd> (Chrome/Windows) 可以随时暂停 JS 的执行。这样您就可以检查 DOM 的快照，而不必担心 JS 会改变 DOM 或事件（如鼠标悬停）会导致 DOM 从您脚下发生变化。
```

2024-05-06 18:55 UTC, TechQuery commented on _posts/Article/Translation/browser-debugging-tricks.md
> +为了检查元素，您可以将以下内容粘贴到控制台中：`setTimeout(function(){debugger; }, 5000);`。这将为您提供 5 秒钟的时间来触发用户界面，一旦 5 秒计时器计时结束，JS 的执行就会暂停，元素也不会消失。您可以自由地将鼠标移到开发工具上，而不会丢失元素：
```suggestion
为了检查元素，您可以将以下内容粘贴到控制台中：`setTimeout(function () { debugger; }, 5000);`。这将为您提供 5 秒钟的时间来触发用户界面，一旦 5 秒计时器计时结束，JS 的执行就会暂停，元素也不会消失。您可以自由地将鼠标移到开发工具上，而不会丢失元素：
```

2024-05-07 02:46 UTC, luojiyin1987 commented on _posts/Article/Translation/browser-debugging-tricks.md
> +在 DOM 检查器中按下 `ctrl+\` (Chrome/Windows) 可以随时暂停 JS 的执行。这样您就可以检查 DOM 的快照，而不必担心 JS 会改变 DOM 或事件 (如鼠标悬停) 会导致 DOM 从您脚下发生变化。
要写成  <kbd>ctrl</kbd> + <kbd>\\</kbd>  需要转义。

2024-05-07 19:02 UTC, TechQuery approved these changes

2024-05-07 19:02 UTC, merged