Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks
FreeCodeCamp-Chengdu/Wiki pull request #77
Opened 2024-05-13 14:59 UTC by luojiyin1987

@FreeCodeCamp-Chengdu I create a Pull Request to close #issue_number

2024-05-14 14:31 UTC, luojiyin1987 reviewed
fix

2024-05-17 19:37 UTC, TechQuery requested changes

2024-05-17 19:37 UTC, TechQuery commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +# 使用 Caddy 和 CloudFlare 在内网自动签发 https 证书
```suggestion
    - Caddy
    - DevOps
    - Docker
toc: true
---
```

2024-05-17 19:37 UTC, TechQuery commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +2.  域名的 NS 服务器设置为 cloudflare， 配置好，大概一天后生效（保守估计）
```suggestion
1.  Caddy 和 `dns-cloudflare` 插件，需要构建自己的 Docker 镜像
2.  域名的 NS 服务器设置为 CloudFlare， 配置好，大概一天后生效（保守估计）
```

2024-05-17 19:37 UTC, TechQuery commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +在 docker compose 同一层 文件夹里，创建一个 Dockerfile
```suggestion
在 Docker compose 同一层文件夹里，创建一个 Dockerfile：
```

2024-05-17 19:37 UTC, TechQuery commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +github.com/caddy-dns/cloudflare
```suggestion
```Dockerfile
FROM  caddy:builder AS builder

RUN caddy-builder github.com/caddy-dns/cloudflare
```

2024-05-17 19:37 UTC, TechQuery commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +CLOUDFLARE_API_TOKEN = your token
```suggestion
```ini
CLOUDFLARE_API_TOKEN = your token
```

2024-05-17 19:37 UTC, TechQuery commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +```
语法名不对

2024-05-17 19:37 UTC, TechQuery commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +        name: caddy
网络是依赖项（且内容少），声明在上方。

2024-05-17 19:37 UTC, TechQuery commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +├── Caddyfile
```suggestion
```text
├── Caddyfile
```

2024-05-17 19:37 UTC, TechQuery commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +aria-hidden="true">配置内网域名解析</figcaption>
```suggestion
<figcaption>配置内网域名解析</figcaption>
```

2024-05-18 01:19 UTC, luojiyin1987 commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +```
看不出来

2024-05-18 07:59 UTC, TechQuery commented on _posts/Article/Engineering/Using-Caddy-and-cloudflare-to-issue-wildcards-on-private-networks.md
> +```
> 看不出来

肯定不是 YAML，先写个 `caddyfile` 的语言名吧，后面哪个 Markdown 解析器支持就直接能高亮。

2024-05-18 11:05 UTC, TechQuery approved these changes

2024-05-18 11:05 UTC, merged