packaging_tools
FreeCodeCamp-Chengdu/Wiki pull request #80
Opened 2024-05-16 15:51 UTC by luojiyin1987

@FreeCodeCamp-Chengdu I create a Pull Request to close #48

2024-05-22 10:02 UTC, TechQuery requested changes
可用 https://git-pager.vercel.app/ 将整篇文章的行内链接收到全文下方。

2024-05-22 15:01 UTC, TechQuery requested changes

2024-05-22 15:01 UTC, TechQuery commented on _posts/Article/Translation/packaging_tools.md
> +date: 8月24, 2023
```suggestion
date: 2023-08-24
```
程序识读的都是 ISO 标准时间格式。

2024-05-22 15:04 UTC, TechQuery commented
前面两个未解决的点行首多出来的空格是手机客户端的 bug，但大小写是没错的。

2024-05-22 19:09 UTC, TechQuery approved these changes

2024-05-25 11:09 UTC, too commented on _posts/Article/Translation/packaging_tools.md
> +### virtualEnv
这里的大写字母没有必要，不规范

2024-05-25 11:09 UTC, too commented on _posts/Article/Translation/packaging_tools.md
>  ## Recap I - `pyproject.toml`
这里的 recap 需要翻译

2024-05-25 11:10 UTC, too commented on _posts/Article/Translation/packaging_tools.md
> +## (Virtual) environment management（虚拟环境管理）
是否用英文来做注释补充更好？或者不要英文了

2024-05-25 11:14 UTC, too commented on _posts/Article/Translation/packaging_tools.md
> +#### Lock file（锁定文件）
这两个地方我觉得都可以去掉英文

2024-05-25 11:14 UTC, too commented on _posts/Article/Translation/packaging_tools.md
> +#### Build/publish flow（构建/发布流程）
同上

2024-05-25 11:14 UTC, too commented on _posts/Article/Translation/packaging_tools.md
> +#### Lock file（锁定文件）
同上

2024-05-25 11:14 UTC, too commented on _posts/Article/Translation/packaging_tools.md
> +#### Build/publish flow（构建/发布流程）
同上

2024-05-25 11:15 UTC, too commented on _posts/Article/Translation/packaging_tools.md
> +#### Build/publish flow（构建/发布流程）
同上

2024-05-25 11:15 UTC, too commented on _posts/Article/Translation/packaging_tools.md
> +#### Declarative environment management（声明式环境管理）
同上

2024-05-25 11:15 UTC, too commented on _posts/Article/Translation/packaging_tools.md
> +#### Build/publish flow（构建/发布流程）
同上

2024-05-25 14:03 UTC, luojiyin1987 commented on _posts/Article/Translation/packaging_tools.md
> +## (Virtual) environment management（虚拟环境管理）
我倾向是用中文做注释

2024-05-25 14:06 UTC, luojiyin1987 commented on _posts/Article/Translation/packaging_tools.md
> +#### Build/publish flow（构建/发布流程）
我建议保留，  很多人对 flow ，不会直接想到中文里的 流程  一词。

2024-05-25 17:16 UTC, too commented on _posts/Article/Translation/packaging_tools.md
> +#### Build/publish flow（构建/发布流程）
我没理解，难道翻译出来不是给中文的阅读者看嘛？为什么要考虑中文阅读者对flow 的联想？

2024-05-26 02:58 UTC, too commented
经过建议，译者认为部分英文需要保留不翻译或附在原文，我尊重译者选择，保留意见。辛苦了

2024-05-26 02:58 UTC, merged

2024-05-26 03:40 UTC, luojiyin1987 commented on _posts/Article/Translation/packaging_tools.md
> +#### Build/publish flow（构建/发布流程）
正是给中文用户去阅读， 就应该保留， 方便他们去查询。