Everything i know about ssd
FreeCodeCamp-Chengdu/Wiki pull request #82
Opened 2024-05-25 06:43 UTC by luojiyin1987

@FreeCodeCamp-Chengdu I create a Pull Request to close #74

2024-06-25 18:50 UTC, TechQuery commented
@luojiyin1987 处理冲突

2024-06-26 05:46 UTC, luojiyin1987 commented
@TechQuery  已经解决冲突

2024-06-26 14:04 UTC, TechQuery requested changes

2024-06-26 14:04 UTC, TechQuery commented on _posts/Article/Translation/everything-I-know-about-ssd.md
> +## 2D 和 3D, 和 Layers（层）
```suggestion
## 2D、 3D 和 Layers（层）
```

2024-06-26 14:04 UTC, TechQuery commented on _posts/Article/Translation/everything-I-know-about-ssd.md
> +## SLC, MLC, TLC, QLC 及其未来发展
```suggestion
## SLC、MLC、TLC、QLC 及其未来发展
```

2024-06-26 14:04 UTC, TechQuery commented on _posts/Article/Translation/everything-I-know-about-ssd.md
> +**为什么空代表一？**
```suggestion
### 为什么空代表一？
```

2024-06-26 14:04 UTC, TechQuery commented on _posts/Article/Translation/everything-I-know-about-ssd.md
> +## 文件系统 - 非眼见为实
```suggestion
## 文件系统 —— 非眼见为实
```

2024-06-26 18:13 UTC, TechQuery approved these changes

2024-06-26 18:14 UTC, merged