Recent docker build kit featuresget
FreeCodeCamp-Chengdu/Wiki pull request #89
Opened 2024-06-05 03:38 UTC by luojiyin1987

@FreeCodeCamp-Chengdu I create a Pull Request to close #84

2024-06-25 18:50 UTC, TechQuery commented
@luojiyin1987 处理冲突

2024-06-26 05:43 UTC, luojiyin1987 commented
@TechQuery  已经解决冲突

2024-06-26 14:41 UTC, TechQuery requested changes

2024-06-26 14:41 UTC, TechQuery commented on _posts/Article/Translation/Recent-Docker-BuildKit-Features.md
> +# 你可能错过的 Docker BuildKit 新功能
```suggestion
```
元数据中的标题会自动渲染。

2024-06-26 14:41 UTC, TechQuery commented on _posts/Article/Translation/Recent-Docker-BuildKit-Features.md
> +[+] Building 1.2s (14/18)                docker:default
命令和文字输出分开。

2024-06-26 14:41 UTC, TechQuery commented on _posts/Article/Translation/Recent-Docker-BuildKit-Features.md
> +```shell
```suggestion
```Dockerfile
```

2024-06-26 14:41 UTC, TechQuery commented on _posts/Article/Translation/Recent-Docker-BuildKit-Features.md
> +
```suggestion
eot
```

2024-06-26 14:42 UTC, TechQuery commented
@luojiyin1987 用工具把所有链接转化为文末引用形式：https://oss-toolbox.kaiyuanshe.cn/article/editor

2024-06-26 15:34 UTC, luojiyin1987 commented on _posts/Article/Translation/Recent-Docker-BuildKit-Features.md
> +
？

2024-06-26 18:19 UTC, TechQuery requested changes

2024-06-26 18:19 UTC, TechQuery commented on _posts/Article/Translation/Recent-Docker-BuildKit-Features.md
> + => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a8...1e24ef1a0dbc
命令、输出分开（下同，自行检查）

2024-06-26 18:19 UTC, TechQuery commented on _posts/Article/Translation/Recent-Docker-BuildKit-Features.md
> +FROM ...
```suggestion
```Dockerfile
# syntax=docker/dockerfile:1.3
FROM ...
```
（下同，自行检查）

2024-06-27 14:35 UTC, TechQuery approved these changes

2024-06-27 14:35 UTC, merged