[翻译] 如何快速学习
FreeCodeCamp-Chengdu/Wiki pull request #98
Opened 2024-06-24 04:43 UTC by dethan3

@FreeCodeCamp-Chengdu I create a Pull Request to close #96

2024-06-24 15:07 UTC, tianheg requested changes

2024-06-24 15:07 UTC, tianheg commented on _drafts/Article/Translation/how-to-learn-stuff-quickly.md
> +有_很多_好处于公开学习，但这里是我发现的一些：
```suggestion
在公共场合学习有_很多_好处，我发现了以下几点：
```

2024-06-24 15:07 UTC, tianheg commented on _drafts/Article/Translation/how-to-learn-stuff-quickly.md
> +我能够如此快速地学习，是因为遵循了这篇博文中列出的所有技术。但还有一个我手中的王牌：_互补技能_。
```suggestion
我能够如此快速地学习，是因为遵循了这篇博文中列出的所有技巧。但还有一个我手中的王牌：_互补技能_。
```

2024-06-24 15:07 UTC, tianheg commented on _drafts/Article/Translation/how-to-learn-stuff-quickly.md
> +事情是这样的，3D 插图不是一项单一的技能；它是由几十项个人技能组成的集合。其中一些，比如创建 3D 模型，对我来说是全新的，我必须从头学起。但其中一些是我有经验的技能网络的一部分。
```suggestion
事情是这样的，3D 插图不是一项单一的技能；它是多个技能组成的集合。其中一些，比如创建 3D 模型，对我来说是全新的，我必须从头学起。但其中一些是我有经验的技能网络的一部分。
```

2024-06-24 15:07 UTC, tianheg commented on _drafts/Article/Translation/how-to-learn-stuff-quickly.md
> +例如：我有点业余摄影师。几年前，我学会了构图，如何在视口中排列元素以获得引人注目的镜头。我可以在我的渲染中定位对象时利用这些技能。
```suggestion
例如：我有点业余摄影爱好。几年前，我学会了构图，如何在视口中排列元素以获得引人注目的镜头。我可以在我的渲染中定位对象时利用这些技能。
```

2024-06-25 00:59 UTC, dethan3 commented on _drafts/Article/Translation/how-to-learn-stuff-quickly.md
> +有_很多_好处于公开学习，但这里是我发现的一些：
```suggested
公开学习有_很多_好处，我发现了以下几点：
```

2024-06-25 01:33 UTC, merged

2024-06-26 00:35 UTC, dethan3 commented
> @dethan3 尚未合并的 PR 涉及的文件不能移动，否则就有一大堆冲突，我已在下个 PR 修复。

好的，谢谢，我记住了